steps:
  - name: "lint"
    command: "make lint"

  - name: "test"
    command: "make test"

  - name: "check fmt"
    command: "make fmt"

  - wait

  - name: ":golang: build"
    command: "make build"

  - wait

  - name: ":rocket: deploy to test"
    command: "ENV=test make deploy"
