steps:
  - name: "lint"
    command: "make lint"

  - name: "test"
    command: "make test"

  - name: "check fmt"
    command: "make fmt"

  - wait

  - name: ":golang: build"
    command:
      - "make build"
      - "tar -cvf build.tar.gz bin"
    artifact_paths:
      - "build.tar.gz"

  - wait

  - name: ":rocket: test"
    command:
      - "mkdir bin"
      - "buildkite-agent artifact download build.tar.gz bin/"
      - "ENV=test make deploy"

  - wait

  - name: ":aws-lambda: integration tests"
    command: "echo 'fake running integration tests'"

  - wait

  - name: ":rocket: stage"
    branches: "master"
    command:
      - "mkdir bin"
      - "buildkite-agent artifact download build.tar.gz bin/"
      - "ENV=stage make deploy"

  - block: "release to prod?"
    branches: "master"
    fields:
      - text: "Code Name"
        key: "release-name"
        hint: "What’s the code name for this release? :name_badge:"
        required: false
        default: "Release #"
      - select: "Stream"
        key: "release-stream"
        options:
          - label: "Beta"
            value: "beta"
          - label: "Stable"
            value: "stable"

  - name: ":rocket: prod"
    branches: "master"
    command:
      - "mkdir bin"
      - "buildkite-agent artifact download build.tar.gz bin/"
      - "ENV=prod make deploy"
